apiVersion: v2
name: nifi
description: A Helm chart for Apache NiFi on Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nifi
    version: ~0.8.0
    repository: https://cetic.github.io/helm-charts
