nifi:
  replicaCount: 1

  ## Image configuration
  image:
    repository: apache/nifi
    tag: "1.16.0"

  ## Service configuration
  service:
    type: ClusterIP
    port: 8080

  ## Persistence configuration
  persistence:
    enabled: true
    size: 10Gi

  ## Security configuration
  properties:
    webProxyHost: "localhost:9090"
    isNode: true
    authorizer: managed-authorizer
    securityUserLogin: true
    securityUserAuthorities: ROLE_ADMIN
    securityUserName: admin
    securityUserPassword: nifiPassword

  ## Resource configuration
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
