nifi:
  replicaCount: 3

  ## Image configuration
  image:
    repository: apache/nifi
    tag: "1.23.2"

  ## Service configuration
  service:
    type: ClusterIP
    httpsPort: 8443

  ## Persistence configuration
  persistence:
    enabled: true

  ## Security configuration
  auth:
    singleUser:
      username: admin
      password: nifiPassword

  ## Cluster configuration
  properties:
    isNode: true
    clusterPort: 6007
    zkClientEnsembleTraker: true
    webProxyHost: nifi.nifi.svc.cluster.local:8443

  ## Zookeeper configuration
  zookeeper:
    enabled: true
    replicaCount: 3

  ## Resource configuration
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
