nifi:
  replicaCount: 3

  ## Image configuration
  image:
    repository: apache/nifi
    tag: "1.23.2"

  ## Service configuration
  service:
    type: ClusterIP
    httpsPort: 8443

  ## Security configuration
  auth:
    singleUser:
      username: admin
      password: nifiPassword # At least 12 characters

  ## Persistence configuration
  persistence:
    enabled: true

  ## Use cert-manager to handle certificates
  certManager:
    enabled: true
    clusterDomain: cluster.local
    keystorePasswd: nifiPassword
    truststorePasswd: nifiPassword
    # Add hostnames for all nodes
    additionalDnsNames:
      - localhost
      - nifi.nifi.svc.cluster.local
      - "*.nifi-headless.nifi.svc.cluster.local"

  ## Cluster configuration
  properties:
    isNode: true
    clusterPort: 6007
    webProxyHost: nifi.nifi.svc.cluster.local:8443

  ## Resource configuration
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
