nifi:
  replicaCount: 3

  ## Image configuration
  image:
    repository: apache/nifi
    tag: "1.23.2"

  ## Service configuration
  service:
    type: ClusterIP
    port: 8080

  ## Persistence configuration
  persistence:
    enabled: true
    size: 10Gi

  ## Security configuration
  properties:
    webProxyHost: "localhost:9090"
    isNode: true
    authorizer: managed-authorizer
    securityUserLogin: true

  ## Resource configuration
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  auth:
    singleUser:
      username: admin
      password: developer2025
