name: Validate Helm Charts

on:
  push:
    paths:
      - "charts/**"
      - ".github/workflows/helm-validate.yml"
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.3"

      - name: Add Helm repositories
        run: |
          helm repo add cetic https://cetic.github.io/helm-charts
          helm repo update

      - name: Lint NiFi Helm chart
        run: |
          cd charts/nifi
          helm dependency build
          helm lint .

      - name: Run Helm Template Validation
        run: |
          cd charts/nifi
          mkdir -p .validation
          helm template . --output-dir .validation

      - name: Validate Kubernetes manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: charts/nifi/.validation/**/*.yaml
          ignore_missing_schemas: true
          strict: true
          version: 1.25.0

      - name: Check for sensitive information
        run: |
          cd charts/nifi
          if grep -r "developer2025" --include="*.yaml" --include="*.yml" .; then
            echo "Warning: Potential hardcoded secrets found in chart files"
            exit 1
          fi
